name: Build Tauri App

on:
  workflow_dispatch:  # Позволяет запускать вручную
  push:
    branches:
      - main  # Запуск при коммите в main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          # Обновление списка пакетов
          sudo apt update
          
          # Установка зависимостей для сборки C и Rust-библиотек
          sudo apt install -y \
            libgtk-3-dev \
            pkg-config \
            libxml2-dev \
            libsoup2.4-dev \
            build-essential \
            libssl-dev \
            libglib2.0-dev \
            libdbus-1-dev \
            libgirepository1.0-dev \
            libcurl4-openssl-dev \
            libpq-dev \
            libsecret-1-dev \
            libicu-dev \
            libgtk-3-dev \
            libayatana-appindicator3-1 \
            libxss1 \
            libnotify-dev \
            libnss3 \
            libxtst6

          # Проверка установки библиотек
          dpkg -l | grep -E "libgtk|libsoup|libxml|pkg-config|libssl|libcurl|libpq"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install npm dependencies
        run: npm install

      - name: Set PKG_CONFIG_PATH environment variable
        run: echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig" >> $GITHUB_ENV

      - name: Build Tauri App with verbose output
        run: |
          # Очистка и сборка с подробным выводом
          cd src-tauri
          cargo clean
          npm run tauri build --verbose

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: tauri-app
          path: src-tauri/target/release/bundle/

      - name: Check for errors in build logs
        run: |
          # Анализ логов на наличие ошибок
          tail -n 50 src-tauri/target/debug/build/log.txt